apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: "{{ .Values.jaeger.image }}"
        ports:
        - containerPort: {{ .Values.jaeger.ports.ui }}
        - containerPort: {{ .Values.jaeger.ports.zipkin }}
        - containerPort: {{ .Values.jaeger.ports.agent }}
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
